import { StyleSheet } from 'react-native';
import { colors } from '../../../constants/theme';

const styles = StyleSheet.create({
  heartPopup: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: '50%',
    left: '50%',
    marginLeft: -11,
    marginTop: -11,
    zIndex: 999,
  },
  flashOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.accent,
    borderRadius: 20,
    zIndex: 5,
  },

  newRibbon: {
    position: 'absolute',
    top: 12,
    left: -44,
    width: 140,
    backgroundColor: colors.accent,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '-45deg' }],
    zIndex: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(0,0,0,0.25)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.55,
    shadowRadius: 4,
    elevation: 8,
  },
  newRibbonText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textOnAccent,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  newRibbonFoldLeft: {
    position: 'absolute',
    left: 0,
    bottom: -10,
    width: 0,
    height: 0,
    borderTopWidth: 10,
    borderTopColor: 'rgba(0,0,0,0.35)',
    borderLeftWidth: 12,
    borderLeftColor: 'transparent',
  },
  newRibbonFoldRight: {
    position: 'absolute',
    right: 0,
    bottom: -10,
    width: 0,
    height: 0,
    borderTopWidth: 10,
    borderTopColor: 'rgba(0,0,0,0.35)',
    borderRightWidth: 12,
    borderRightColor: 'transparent',
  },
  wishlistRibbon: {
    position: 'absolute',
    top: 12,
    left: -44,
    width: 140,
    backgroundColor: colors.accent,
    paddingVertical: 7,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(0,0,0,0.25)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.55,
    shadowRadius: 4,
    elevation: 8,
  },
  wishlistRibbonFoldLeft: {
    position: 'absolute',
    left: 0,
    bottom: -10,
    width: 0,
    height: 0,
    borderTopWidth: 10,
    borderTopColor: 'rgba(0,0,0,0.35)',
    borderLeftWidth: 12,
    borderLeftColor: 'transparent',
  },
  wishlistRibbonFoldRight: {
    position: 'absolute',
    right: 0,
    bottom: -10,
    width: 0,
    height: 0,
    borderTopWidth: 10,
    borderTopColor: 'rgba(0,0,0,0.35)',
    borderRightWidth: 12,
    borderRightColor: 'transparent',
  },
  wishlistRibbonText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textOnAccent,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  cardWrapper: {
    marginBottom: 14,
    borderRadius: 20,
    shadowColor: 'rgba(240, 184, 64, 1)',
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 18,
  },
  itemCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
  },
  itemCardNew: {},
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.glassHighlight,
  },
  typeTag: {
    backgroundColor: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  typeText: {
    color: colors.textOnAccent,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  statText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  statTextActive: {
    color: colors.accent,
  },
  cardContent: {
    flexDirection: 'row',
    padding: 16,
  },
  imageContainer: {
    width: 100,
    height: 100,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 1,
    borderColor: colors.borderAlt,
  },
  itemImage: {
    width: 80,
    height: 80,
  },
  itemInfo: {
    flex: 1,
    justifyContent: 'flex-start',
    gap: 4,
  },
  nameAndLikes: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  nameContainer: {
    flex: 1,
  },
  itemName: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 2,
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 0,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  priceLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '600',
  },
  priceLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  creditIcon: {
    width: 18,
    height: 18,
  },
  ducatIcon: {
    width: 18,
    height: 18,
  },
  priceValue: {
    fontSize: 16,
    color: colors.textLight,
    fontWeight: '700',
  },
  ducatValue: {
    fontSize: 16,
    color: colors.accent,
    fontWeight: '700',
  },
});

export default styles;
