import { StyleSheet } from 'react-native';
import { colors } from '../../../constants/theme';

const styles = StyleSheet.create({
  heartPopup: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: '50%',
    left: '50%',
    marginLeft: -40,
    marginTop: -40,
    zIndex: 999,
  },
  newBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    marginBottom: -1,
    marginLeft: 0,
    zIndex: 1,
  },
  newBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textOnAccent,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  wishlistBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    marginBottom: -1,
    marginLeft: 0,
    zIndex: 1,
  },
  wishlistBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textOnAccent,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  itemCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  itemCardNew: {
    borderTopLeftRadius: 0,
    borderColor: colors.accent,
    borderWidth: 2,
  },
  itemCardWishlist: {
    borderTopLeftRadius: 0,
    borderColor: colors.accent,
    borderWidth: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.border,
  },
  typeTag: {
    backgroundColor: colors.accent,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  typeText: {
    color: colors.textOnAccent,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statsContainer: {
    gap: 4,
    alignItems: 'flex-end',
  },
  likesContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  likesText: {
    color: colors.accent,
    fontSize: 16,
    fontWeight: '600',
  },
  reviewsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reviewsText: {
    color: colors.accent,
    fontSize: 15,
    fontWeight: '600',
  },
  wishlistCountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  wishlistCountText: {
    color: colors.accent,
    fontSize: 15,
    fontWeight: '600',
  },
  cardContent: {
    flexDirection: 'row',
    padding: 16,
  },
  imageContainer: {
    width: 100,
    height: 100,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    borderWidth: 1,
    borderColor: colors.borderAlt,
  },
  itemImage: {
    width: 80,
    height: 80,
  },
  itemInfo: {
    flex: 1,
    justifyContent: 'flex-start',
    gap: 4,
  },
  nameAndLikes: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  nameContainer: {
    flex: 1,
    marginRight: 8,
  },
  itemName: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 2,
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 0,
  },
  priceContainer: {
    gap: 8,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  priceLabel: {
    fontSize: 13,
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '600',
  },
  priceLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  creditIcon: {
    width: 18,
    height: 18,
  },
  ducatIcon: {
    width: 18,
    height: 18,
  },
  priceValue: {
    fontSize: 16,
    color: colors.textLight,
    fontWeight: '700',
  },
  ducatValue: {
    fontSize: 16,
    color: colors.accent,
    fontWeight: '700',
  },
});

export default styles;
